import pytest
from datetime import datetime, timezone
from fastapi.testclient import TestClient

from app.main import app
from app.models.schemas import EvidenceItem, EvidenceType

client = TestClient(app)

def test_case_evidence_flows_to_analysis(monkeypatch):
    """
    Verifies that evidence generated by the Case module is correctly retrieved 
    and processed by the Analysis pipeline, without requiring any pipeline changes.
    """

    # 1. Create mock CASE_WORK_SAMPLE evidence
    case_evidence = EvidenceItem(
        id="case-ev-123",
        candidate_id="CAND-TEST",
        source="consulting_case",
        evidence_type=EvidenceType.CASE_WORK_SAMPLE,
        text="Candidate provided a strong structural breakdown of the ML pipeline.",
        competency_ids=["C13"],
        canonical_competency_ids=["C13"],
        confidence=0.85,
        created_at=datetime.now(timezone.utc),
        source_version="case-v1.0"
    )

    # 2. Mock get_candidate_evidence to return this evidence
    monkeypatch.setattr(
        "app.api.analysis.get_candidate_evidence",
        lambda cid: [case_evidence] if cid == "CAND-TEST" else []
    )

    # 3. Mock get_candidate_attempts so the diagnostic filter doesn't break
    class MockAttempt:
        def __init__(self):
            self.id = "ATT-123"
            self.status = "completed"
            self.attempt_number = 1
            self.evidence_ids = []
            self.previous_attempt_id = None
            
    monkeypatch.setattr(
        "app.api.analysis.get_candidate_attempts",
        lambda cid: [MockAttempt()]
    )
    
    # 4. Mock the LLM EvidenceMapperAgent to prevent real LLM calls during test
    class MockEvidenceMapper:
        def evaluate(self, evidence_list):
            from app.models.schemas import CompetencyEvaluation
            # Return a mock evaluation pointing to the case evidence
            return [
                CompetencyEvaluation(
                    competency_id="C13",
                    score=85,
                    confidence=0.9,
                    evidence_ids=[e.id for e in evidence_list]
                )
            ]
            
    monkeypatch.setattr("app.api.analysis.EvidenceMapperAgent", MockEvidenceMapper)
    
    # 5. Mock get_evidence_by_ids to return the item
    monkeypatch.setattr(
        "app.api.analysis.get_evidence_by_ids",
        lambda ev_ids: [case_evidence] if "case-ev-123" in ev_ids else []
    )
    
    # 6. Mock get_latest_portfolio_intelligence to return nothing
    monkeypatch.setattr(
        "app.api.analysis.get_latest_portfolio_intelligence",
        lambda cid: None
    )

    # 7. Mock analysis save
    saved_analyses = []
    monkeypatch.setattr(
        "app.api.analysis.save_analysis",
        lambda cid, analysis: saved_analyses.append(analysis)
    )

    monkeypatch.setattr("app.api.analysis.save_review_decision", lambda decision: None)

    # 8. Hit the analysis endpoint
    response = client.post("/api/analysis/CAND-TEST")
    
    # 9. Assertions
    assert response.status_code == 200
    
    analysis_data = response.json()
    assert analysis_data["candidate_id"] == "CAND-TEST"
    
    # Check evidence coverage includes our case evidence
    # Since we mocked the mapper to map it, it should be in the evaluations
    assert len(analysis_data["evaluations"]) > 0
    
    # Check that provenance is preserved in 'evidence_details'
    eval_payload = analysis_data["evaluations"][0]
    assert len(eval_payload["evidence_details"]) > 0
    evidence_detail = eval_payload["evidence_details"][0]
    
    assert evidence_detail["id"] == "case-ev-123"
    assert evidence_detail["source"] == "consulting_case"
    assert evidence_detail["evidence_type"] == "case_work_sample"

    # Ensure duplicate handling works inherently - fetching the same item multiple times
    # doesn't create duplicate items in the output if it's the same ID.
    assert len([e for e in eval_payload["evidence_details"] if e["id"] == "case-ev-123"]) == 1
