import json

from pathlib import Path
from typing import List, Optional

from app.models.schemas import AssessmentAttempt


DATA_DIR = Path(__file__).resolve().parents[2] / "data"
ATTEMPTS_FILE = DATA_DIR / "assessment_attempts.json"


def _ensure_store():
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    if not ATTEMPTS_FILE.exists():
        ATTEMPTS_FILE.write_text("[]", encoding="utf-8")


def _load_attempts() -> List[dict]:
    _ensure_store()

    return json.loads(
        ATTEMPTS_FILE.read_text(encoding="utf-8")
    )


def _save_attempts(attempts: List[dict]):
    _ensure_store()

    ATTEMPTS_FILE.write_text(
        json.dumps(attempts, indent=2),
        encoding="utf-8",
    )


def create_attempt(
    attempt: AssessmentAttempt,
) -> AssessmentAttempt:
    """
    Create a new assessment attempt.

    Once created, the attempt's evidence and assessment identity
    are preserved. Only lifecycle metadata such as status,
    completion time, and evidence IDs may be updated.
    """

    attempts = _load_attempts()

    attempts.append(
        attempt.model_dump(mode="json")
    )

    _save_attempts(attempts)

    return attempt


def update_attempt_status(
    attempt_id: str,
    status: str,
    completed_at=None,
) -> Optional[AssessmentAttempt]:
    """
    Update the lifecycle status of an assessment attempt.

    Valid statuses used by the prototype:
        in_progress
        completed
        failed

    This does not overwrite the assessment attempt with a new
    attempt. It only updates lifecycle metadata.
    """

    attempts = _load_attempts()

    for item in attempts:

        if item["id"] != attempt_id:
            continue

        item["status"] = status

        if completed_at is not None:
            item["completed_at"] = completed_at.isoformat()

        _save_attempts(attempts)

        return AssessmentAttempt(**item)

    return None


def get_attempt(
    attempt_id: str,
) -> Optional[AssessmentAttempt]:

    attempts = _load_attempts()

    for item in attempts:

        if item["id"] == attempt_id:
            return AssessmentAttempt(**item)

    return None


def get_candidate_attempts(
    candidate_id: str,
) -> List[AssessmentAttempt]:

    attempts = _load_attempts()

    return [
        AssessmentAttempt(**item)
        for item in attempts
        if item["candidate_id"] == candidate_id
    ]


def get_latest_attempt(
    candidate_id: str,
) -> Optional[AssessmentAttempt]:

    attempts = get_candidate_attempts(candidate_id)

    if not attempts:
        return None

    return max(
        attempts,
        key=lambda attempt: attempt.attempt_number,
    )


def update_attempt_evidence(
    attempt_id: str,
    evidence_ids: List[str],
) -> Optional[AssessmentAttempt]:
    """
    Persist the evidence IDs generated by an assessment attempt.

    Evidence records themselves are stored separately. This function
    keeps the assessment attempt explicitly linked to the evidence
    it produced.
    """
    attempts = _load_attempts()

    for item in attempts:
        if item["id"] != attempt_id:
            continue

        existing_ids = item.get("evidence_ids", [])

        # Preserve existing IDs and avoid duplicates.
        item["evidence_ids"] = list(
            dict.fromkeys(existing_ids + evidence_ids)
        )

        _save_attempts(attempts)

        return AssessmentAttempt(**item)

    return None
